import { ReactNode, useEffect, useState } from 'react';
import Head from 'next/head'
import { Footer } from '@/components/ui/Footer'
import { Contact } from '@/components/ui/Contact';
import { NavFeatures } from '@/components/ui/navigation/Nav_Features'
import ReactGA from 'react-ga';

type ILayoutProps = {
  children?: ReactNode | undefined;
};

export default function Layout({ children }: ILayoutProps) {
  ReactGA.initialize('G-DXKFRZ3S9W');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavFeatures />
      <Contact />
      <main role='document' className={`container Main__Wrapper fadeIn`}>
        {children}
      </main>

      <Footer />
    </>
  )
}
