import { ReactNode, useEffect, useState } from 'react';
import Head from 'next/head'
import { Footer } from '@/components/ui/Footer'

type ILayoutProps = {
  children?: ReactNode | undefined;
};


export default function Layout({ children }: ILayoutProps) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar /> */}
      <main role='document' className={`container Main__Wrapper fadeIn`}>
        {children}
      </main>

      <Footer />
    </>
  )
}
