import React from 'react';
import Head from 'next/head';
import propTypes from "prop-types";


export default function Header ({page}) {
  // const router = useRouter();

  return (
    <>
      <Head>
        <title>{page}</title>
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta name="description" content="Generated by create next app" />
      </Head>
    {/* <header>
    </header> */}
  </>
  )
}

// proptypes check
Header.propTypes = {
  page: propTypes.string,
};